steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:$COMMIT_SHA'
      - '-t'
      - 'us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:latest'
      - '.'
    id: 'Build Docker Image'

  # 2. Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:$COMMIT_SHA'
    id: 'Push Commit SHA Tag'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:latest'
    id: 'Push Latest Tag'

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'audio-manga' # Your Cloud Run service name
      - '--image'
      - 'us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:$COMMIT_SHA'
      - '--region'
      - 'us-east4' # The region of your Cloud Run service
      - '--service-account'
      - 'main-app-account@inspired-parsec-454518-p7.iam.gserviceaccount.com'
      - '--update-secrets=APPLICATION_ENV_SECRET=ENV:latest' # Reference your secret
      - '--quiet'
    id: 'Deploy to Cloud Run'

# Define the image tags
images:
  - 'us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:$COMMIT_SHA'
  - 'us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:latest'

# Optional: Timeout for the build
timeout: '1200s' # 20 minutes

# Options for logging
options:
  logging: CLOUD_LOGGING_ONLY
