steps:
  # 1. Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: bash
    args:
      - '-c'
      - |
        # The NEXT_PUBLIC_ variables are now directly available in this shell's environment
        # because of the secretEnv declaration below.
        # We still need to pass them as build-args to the Dockerfile.
        docker build \
          --build-arg BUILD_TIME_NEXT_PUBLIC_SUPABASE_URL="$$NEXT_PUBLIC_SUPABASE_URL" \
          --build-arg BUILD_TIME_NEXT_PUBLIC_SUPABASE_ANON_KEY="$$NEXT_PUBLIC_SUPABASE_ANON_KEY" \
          -t us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:$COMMIT_SHA \
          -t us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:latest \
          .
    id: 'Build Docker Image'
    # This makes the secrets available as environment variables to THIS build step's execution environment.
    # The names here (NEXT_PUBLIC_SUPABASE_URL, NEXT_PUBLIC_SUPABASE_ANON_KEY) are what we'll use in $$...
    secretEnv: ['NEXT_PUBLIC_SUPABASE_URL', 'NEXT_PUBLIC_SUPABASE_ANON_KEY']

  # 2. Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:$COMMIT_SHA'
    id: 'Push Commit SHA Tag'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:latest'
    id: 'Push Latest Tag'

  # 3. Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'audio-manga-app' # Your Cloud Run service name
      - '--image'
      - 'us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:$COMMIT_SHA'
      - '--region'
      - 'us-east4' # The region of your Cloud Run service
      - '--service-account'
      - 'main-app-account@inspired-parsec-454518-p7.iam.gserviceaccount.com'
      - '--clear-secrets' # Clear existing secrets before updating
      # Replace with your actual environment variables and secret names
      - '--update-secrets=NODE_ENV=NODE_ENV_SECRET:latest,NEXT_PUBLIC_SUPABASE_ANON_KEY=NEXT_PUBLIC_SUPABASE_ANON_KEY_SECRET:latest,NEXT_PUBLIC_SUPABASE_URL=NEXT_PUBLIC_SUPABASE_URL_SECRET:latest,POSTGRES_DATABASE=POSTGRES_DATABASE_SECRET:latest,POSTGRES_HOST=POSTGRES_HOST_SECRET:latest,POSTGRES_PASSWORD=POSTGRES_PASSWORD_SECRET:latest,POSTGRES_PRISMA_URL=POSTGRES_PRISMA_URL_SECRET:latest,POSTGRES_URL=POSTGRES_URL_SECRET:latest,POSTGRES_URL_NON_POOLING=POSTGRES_URL_NON_POOLING_SECRET:latest,POSTGRES_USER=POSTGRES_USER_SECRET:latest,SUPABASE_JWT_SECRET=SUPABASE_JWT_SECRET_SECRET:latest,GOOGLE_API_KEY=GOOGLE_API_KEY_SECRET:latest,GOOGLE_API_KEY_2=GOOGLE_API_KEY_2_SECRET:latest,GOOGLE_CLOUD_PROJECT_ID=GOOGLE_CLOUD_PROJECT_ID_SECRET:latest,GOOGLE_CLOUD_BUCKET_NAME=GOOGLE_CLOUD_BUCKET_NAME_SECRET:latest,GCP_PRIVATE_KEY_BASE64=GCP_PRIVATE_KEY_BASE64_SECRET:latest,GCP_PROJECT_ID=GCP_PROJECT_ID_SECRET:latest,GCP_CLIENT_EMAIL=GCP_CLIENT_EMAIL_SECRET:latest,GCP_QUEUE_LOCATION=GCP_QUEUE_LOCATION_SECRET:latest,GCP_QUEUE_ID=GCP_QUEUE_ID_SECRET:latest,GCP_TASK_HANDLER_URL=GCP_TASK_HANDLER_URL_SECRET:latest,GCP_TEMP_UPLOAD_BUCKET_NAME=GCP_TEMP_UPLOAD_BUCKET_NAME_SECRET:latest' # Reference your individual secrets
      - '--quiet'
    id: 'Deploy to Cloud Run'

# Define the image tags
images:
  - 'us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:$COMMIT_SHA'
  - 'us-east4-docker.pkg.dev/inspired-parsec-454518-p7/audio-manga-repo/audio-manga:latest'

# Optional: Timeout for the build
timeout: '1200s' # 20 minutes

# Options for logging
options:
  logging: CLOUD_LOGGING_ONLY

# Define secrets to be made available to the build steps
# Ensure these secrets (SUPABASE_URL_SECRET and SUPABASE_ANON_KEY_SECRET) exist in your Secret Manager
# and that the Cloud Build service account ([PROJECT_NUMBER]@cloudbuild.gserviceaccount.com)
# has the 'Secret Manager Secret Accessor' role for them.
availableSecrets:
  secretManager:
  - versionName: projects/inspired-parsec-454518-p7/secrets/SUPABASE_URL_SECRET/versions/latest
    # Expose the secret directly as NEXT_PUBLIC_SUPABASE_URL to the build step's environment
    env: 'NEXT_PUBLIC_SUPABASE_URL'
  - versionName: projects/inspired-parsec-454518-p7/secrets/SUPABASE_ANON_KEY_SECRET/versions/latest
    # Expose the secret directly as NEXT_PUBLIC_SUPABASE_ANON_KEY to the build step's environment
    env: 'NEXT_PUBLIC_SUPABASE_ANON_KEY'
